CREATE TABLE IF NOT EXISTS comments(
  id SERIAL PRIMARY KEY,
  entry_id INT NOT NULL,
  rank SMALLINT NOT NULL,
  username VARCHAR (100) NOT NULL,
  icon VARCHAR (100) UNIQUE NOT NULL,
  content VARCHAR (100) NOT NULL,
  commented_at DATE NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
