version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - db
    volumes:
      - ./db:/opt/db
    ports:
      - "5000:5000"
  db:
    image: postgres:12
    ports:
      - 5432:5432
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
