version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    env_file: .env
    depends_on:
      - db
    volumes:
      - ./db:/opt/db
    command: ["./start.sh"]
  db:
    image: postgres:12
    ports:
      - 5432:5432
    env_file: .env
